### ISSUE TITLE
Desc. all tools, technology, flow ...

### ISSUE THREAD

**Issue by dfurmans** [Nantiopa/xmundo#3]
Target: better comprehension of all what we have done so far

Tool: https://excalidraw.com/
Format: Tool, Technology etc as a Map defined as elements within relationships.

Drawing:
https://excalidraw.com/#json=0DIYdOjQX6OBybDcUlPIX,7tQjbMK-BG7NRNZBueOJnw

**Comment by dfurmans** [comment]
Thanks @Nantiopa for your solution. 
Going to review it and will let you know here.

**Comment by dfurmans** [comment]
hi!

Please find my questions and further doubts about technology diagram under the link
https://excalidraw.com/#json=ztFMiU6WXX5LDbfEyQ-E6,TQxShSSTjwPZkNqFD4nQqw

In general I would be great if you can map more details, definitions and relations in between each-other, one-another.

If something is not clear, please let me know in this conversation.

Thanks @Nantiopa

**Comment by Nantiopa** [comment]
Thanks @dfurmans 
I added some stuff here, but erased your notes (saved as .jpg to not lose it) as it cannot be saved to different versions without purchasing an excali subscription plan https://excalidraw.com/#json=TQ5gRiLijY4MO5Gly8j7H,I6uA_jdm-j9ROnmIRchOpw 
I can't read all the comments so maybe next time try to use text tool instead of the drawing one ;) We can disscuss the scheme further on on Friday meeting. 
I did not want to put too many lines to not make a hard to read webbing. I'll explain some color code I tried to use with browser/page scheme part 

![Image](https://github.com/Nantiopa/xmundo/assets/157647041/6be951ba-fde9-4ca3-a23a-80132e4309bf)

**Comment by dfurmans** [comment]
Super! You are completely right. I screw-up a little bit the previous one. Too fast too bad. 
Thanks for helping me with that.
Good good good job @Nantiopa 

![image](https://github.com/Nantiopa/xmundo/assets/2587240/50757010-f8da-417d-9ffe-1e8e6f9713bd)

**Comment by dfurmans** [comment]
We have finished the task.
